version: "3"
services:
  core:

    build:
      context: ../../
      dockerfile: environments/Dockerfile

    ports:
      - "7777:8888"
    volumes:
      - ../../:/work

    environment:
      - "NVIDIA_VISIBLE_DEVICES=all"
      - "NVIDIA_DRIVER_CAPABILITIES=all"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
              - gpu
